blank_issues_enabled: false
contact_links:
  - name: Bapecord Support Server
    url: https://discord.gg/S7tx5stnvk
    about: If you need help regarding Vencord, please join our support server!
  - name: Bapecord Installer
    url: https://github.com/bapecord/Bapecord
    about: You can find the Vencord Installer here
